site :opscode

cookbook 'yum'
cookbook 'openssl'
cookbook 'build-essential' # this is for source code for compile
cookbook 'simple_iptables'

cookbook 'git'
cookbook 'vim'

cookbook 'users'
cookbook 'sudo'

cookbook 'ruby_build'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'

cookbook 'nginx'
cookbook 'mongodb', git: 'git@github.com:edelight/chef-mongodb.git', ref: "HEAD"
cookbook 'memcached'
cookbook 'mysql', github: 'opscode-cookbooks/mysql'
cookbook 'monit', git: 'https://github.com/phlipper/chef-monit.git'
cookbook 'chef-redis-server', git: 'https://github.com/huhongda/chef-redis-server.git'

cookbook 'phantomjs'

cookbook 'chef-mongodb', path: 'site-cookbooks/chef-mongodb'
